export { default as IndexPage } from './IndexPage/IndexPage'
export { default as FeedbackPage } from './FeedbackPage/FeedbackPage'
export { default as CoursesPage } from './CoursesPage/CoursesPage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as RegisterPage } from './RegisterPage/RegisterPage'
